apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-core-config
  namespace: risk-platform
data:
  BANKING_CORE_PORT: "8084"
  KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:9092"
  TRANSACTION_EVENTS_TOPIC: "transaction_events"
  FRAUD_API_BASE_URL: "http://fraud-decision-api:8000"
  FRAUD_API_CONNECT_TIMEOUT_MS: "1000"
  FRAUD_API_READ_TIMEOUT_MS: "1500"
  BANKING_CORE_SECURITY_ENABLED: "false"
  SPRING_PROFILES_ACTIVE: "k8s"
  POSTGRES_HOST: "host.docker.internal"
  POSTGRES_PORT: "55432"
  POSTGRES_DB: "transaction_risk"
  POSTGRES_USER: "risk_user"
