apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-core
  namespace: risk-platform
  labels:
    app: banking-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-core
  template:
    metadata:
      labels:
        app: banking-core
    spec:
      containers:
        - name: banking-core
          image: banking-core:local
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8084
          envFrom:
            - configMapRef:
                name: banking-core-config
            - secretRef:
                name: banking-core-secret
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "750m"
              memory: "1Gi"
