apiVersion: v1
kind: Service
metadata:
  name: fraud-decision-api
  namespace: risk-platform
  labels:
    app: fraud-decision-api
spec:
  type: NodePort
  selector:
    app: fraud-decision-api
  ports:
    - name: http
      port: 8000
      targetPort: http
      nodePort: 30080
