apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: risk-platform
  labels:
    app: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8085
      targetPort: http
      nodePort: 30085
