kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: risk-platform
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30084
        hostPort: 18084
        protocol: TCP
      - containerPort: 30085
        hostPort: 18085
        protocol: TCP
      - containerPort: 30080
        hostPort: 18080
        protocol: TCP
